adam_eps: 1.0e-15
adaptive_iters: false
adaptive_range_on: false
affine_exposure_correction: true
begin_frame: 0
behind_dropoff_on: false
bg_color:
- 1.0
- 1.0
- 1.0
bs: 8192
bs_new_sample: 2000
buffer_size: 100000000
calib_path: ''
cam_cad_path: ./cad/camera.ply
cam_pose_train_on: false
color_channel: 3
color_feature_dim: 16
color_map_on: true
color_mlp_hidden_dim: 64
color_mlp_level: 1
color_on: true
consist_wieght_on: false
context_cosdist_threshold: 0.3
context_num_candidates: 1
context_shape:
- 20
- 60
context_virtual_side_count: 10
context_virtual_step_m: 1.0
correction_deg: 0.195
data_loader_name: kitti
data_loader_seq: '06'
decoder_freezed: false
depth_min_accu_alpha: 0.2
deskew: true
deskew_ref_ratio: 0.5
device: cuda
diff_ts_local: 400.0
displacement_range_ratio: 2.0
dist_concat_on: false
dist_weight_on: true
dist_weight_scale: 0.8
dynamic_certainty_thre: 1.0
dynamic_filter_on: false
dynamic_min_grad_norm_thre: 0.25
dynamic_sdf_ratio_thre: 0.8
eigenvalue_check: true
ekional_add_to: all
ekional_loss_on: true
end_frame: 1101
estimate_normal: false
eval_depth_min_accu_alpha: 0.8
eval_traj_align: true
exposure_correction_on: true
feature_dim: 32
feature_std: 0.0
filter_moving_object: true
first_frame_ref: false
free_behind_n: 1
free_front_n: 2
free_sample_begin_ratio: 0.3
free_sample_end_dist_m: 0.8
freespace_label_on: false
freeze_after_frame: 30
from_all_samples: false
from_sample_points: true
gaussian_bs_ratio: 2.0
geo_mlp_hidden_dim: 64
geo_mlp_level: 1
global_loop_on: true
gpu_id: '0'
gradient_decimation: 10
gs_cam_refine_iter_count: 50
gs_consist_depth_fixed: false
gs_consist_normal_fixed: false
gs_consist_shift_count: 0
gs_consist_shift_range_m: 0.15
gs_contribution_threshold: 0.1
gs_down_rate: 1
gs_eval_cam_refine_on: false
gs_eval_on: false
gs_invalid_check_on: true
gs_iters: 50
gs_keyframe_accu_travel_degree: 30.0
gs_keyframe_accu_travel_dist: 1.2
gs_keyframe_interval: 1
gs_mlp_hidden_dim: 128
gs_mlp_level: 1
gs_on: true
gs_type: gaussian_surfel
gs_vis_down_rate: 1
gs_vis_on: true
idw_index: 2
img_pool_size: 20
infer_bs: 65536
init_iter_ratio: 40
inverse_depth_loss: false
iters: 15
keep_local_mesh: false
kitti_correction_on: true
label_path: ''
lambda_area: 0.001
lambda_depth: 0.02
lambda_distort: 0.0
lambda_invalid_opacity: 0.0
lambda_isotropic: 0.0
lambda_mono_normal: 0.01
lambda_normal_depth_consist: 0.01
lambda_normal_smooth: 0.0
lambda_opacity: 0.002
lambda_opacity_ent: 0.0
lambda_sdf: 0.5
lambda_sdf_cons: 0.02
lambda_sdf_normal_cons: 0.02
lambda_sky: 0.001
lambda_ssim: 0.2
lastest_train_prob: 0.1
layer_norm_on: false
learn_color_residual: true
lidar_type_guess: hesai
load_model: false
local_loop_dist_thre: 15.0
local_map_context: true
local_map_context_latency: 5
local_map_default_on: true
local_map_radius: 63.0
local_map_travel_dist_ratio: 5.0
log_freq_frame: 0
logistic_gaussian_ratio: 0.55
long_term_pool_size: 40
long_term_train_down: false
loop_dist_drift_ratio_thre: 2.0
loop_local_map_time_window: 100
loop_with_feature: false
loop_z_check_on: false
loss_weight_on: false
lr_cam_dr: 0.003
lr_cam_dt: 0.001
lr_color: 0.002
lr_exposure: 0.001
lr_geo: 0.002
lr_gs_features: 0.0025
lr_gs_opacity: 0.05
lr_gs_position: 0.00016
lr_gs_rotation: 0.001
lr_gs_scaling: 0.005
lr_mlp_base: 0.01
lr_mlp_gs_alpha: 0.001
lr_mlp_gs_color: 0.01
lr_mlp_gs_rot: 0.001
lr_mlp_gs_scale: 0.001
lr_mlp_gs_xyz: 0.001
main_loss_type: bce
map_surface_ratio: 0.2
mapping_freq_frame: 1
max_prune_certainty: 3.0
max_range: 60.0
max_scale_ratio: 2.0
max_sdf_ratio: 5.0
max_sdf_std_ratio: 1.0
max_z: 60.0
mc_mask_on: true
mc_res_m: 0.15
mesh_default_on: false
mesh_freq_frame: 10
mesh_min_nn: 9
mesh_vis_normal: false
min_alpha: 0.05
min_cluster_vertices: 500
min_loop_travel_dist_ratio: 4.0
min_range: 3.0
min_valid_nn_k: 6
min_visible_neural_point_ratio: 0.1
min_z: -3.5
mlp_bias_on: true
mlp_leaky_relu: false
model_path: /
monodepth_gaussian_res: 1.25
monodepth_on: true
name: 4090_gs_on_mid_s06_test_kitti_gs_kitti_06
neural_point_map_default_on: true
neural_point_vis_down_rate: 7
new_certainty_thre: 1.0
new_sample_ratio_less: 0.02
new_sample_ratio_more: 0.15
new_sample_ratio_restart: 0.3
nothing_new_count_thre: 5
npmc_max_dist: 42.0
num_grad_step_ratio: 0.2
num_nei_cells: 2
num_workers: 12
numerical_grad: true
o3d_vis_on: false
o3d_vis_raw: false
opt_adam: true
output_root: ./pings_experiments/MPINGS
pad_voxel: 3
pc_path: ./data/
pgo_error_thre: 500.0
pgo_error_thre_frame: 500.0
pgo_freq: 30
pgo_max_iter: 50
pgo_merge_map: false
pgo_on: true
pgo_rot_std: 0.01
pgo_tran_std: 0.04
pgo_with_isam: true
pgo_with_pose_prior: false
photometric_loss_on: false
photometric_loss_weight: 0.01
pool_capacity: 10000000
pool_filter_freq: 10
pool_filter_with_dist: false
pose_path: ''
proj_correction_on: false
prune_freq_frame: 100
prune_map_on: false
publish_np_map: true
publish_np_map_down_rate_list:
- 11
- 23
- 37
- 53
- 71
- 89
- 97
- 113
- 131
- 151
query_nn_k: 6
rand_down_r: 1.0
rand_downsample: false
range_filter_2d: true
reg_GM_dist_m: 0.3
reg_GM_grad: 0.1
reg_dist_div_grad_norm: false
reg_iter_n: 50
reg_lm_lambda: 0.0001
reg_max_grad_norm: 2.5
reg_min_grad_norm: 0.4
reg_term_thre_deg: 0.01
reg_term_thre_m: 0.001
rehash_with_time: true
rendered_pc_eval_on: false
republish_raw_input: false
rerender_tsdf_fusion_on: false
rerun_vis_on: false
run_name: 4090_gs_on_mid_s06_test_kitti_gs_kitti_06_2026-04-23_09-38-21
run_path: ./pings_experiments/MPINGS/4090_gs_on_mid_s06_test_kitti_gs_kitti_06_2026-04-23_09-38-21
run_with_ros: false
save_map: false
save_merged_pc: false
save_mesh: false
sdf_default_on: false
sdf_slice_height: -1.0
sdfslice_freq_frame: 1
search_alpha: 0.8
seed: 42
sem_class_count: 20
sem_feature_dim: 8
sem_label_decimation: 1
sem_mlp_hidden_dim: 64
sem_mlp_level: 1
semantic_on: false
sensor_cad_path: ./cad/kitti_car.ply
short_term_train_prob: 0.5
sigma_sigmoid_m: 0.05
silence: false
skip_top_voxel: 2
sorrounding_map_radius: 88.19999999999999
source_vox_down_m: 0.6
spawn_n_gaussian: 8
step_frame: 1
stop_frame_thre: 5
surface_sample_n: 4
surface_sample_range_m: 0.25
temporal_local_map_off: false
timeout_duration_s: 30
track_mask_query_nn_k: 6
track_on: true
train_front_only: true
tsdf_fusion_space_carving_on: false
tsdf_fusion_voxel_size: 0.2
uniform_motion_on: true
unit_scale_ratio: 0.5
use_dataloader: true
use_mid_ts: false
use_reg_cov_mat: false
valid_grad_max_thre: 2.0
valid_grad_min_thre: 0.4
view_concat_on: true
vis_frame_axis_len: 1.2
vis_in_cv2: false
vis_point_size: 2
vis_sdf_res_m: 0.2
vis_sdf_slice_v: false
visualizer_split_width_ratio: 0.7
vox_down_m: 0.05
voxel_size_m: 0.25
wandb_vis_on: false
weight_decay: 0.0
weight_e: 0.5
weight_i: 0.1
weight_s: 1.0
weighted_first: false
window_radius: 63.5
